Repository ISIS3510-202410-Team33/ventura-backend, pull requests merged in 2024-05, with the labels that each got.

#22 Visual improvements to the location rating analytics page
  ventura_backend/Pipfile
  ventura_backend/Pipfile.lock
  ventura_backend/ventura/api/urls.py
  ventura_backend/ventura/templates/base.html
  ventura_backend/ventura/templates/building_ratings.html
  ventura_backend/ventura/templates/get_data.html
  ventura_backend/ventura/templates/index.html
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/settings.py
Labels: enhancement

#24 Fixing most-visited-recommendations method
  ventura_backend/ventura/api/views.py
Labels: bug, enhancement

#27 High Precision Routing (HPR)
  ventura_backend/__init__.py
  ventura_backend/hprouting/dao/building_dao.py
  ventura_backend/hprouting/dao/site_dao.py
  ventura_backend/hprouting/dao/university_dao.py
  ventura_backend/hprouting/logic/__init__.py
  ventura_backend/hprouting/logic/algorithms/graphs.py
  ventura_backend/hprouting/logic/shortest_route.py
  ventura_backend/hprouting/postman/HighPrecisionRoutingTests.postman_collection.json
  ventura_backend/hprouting/postman/Ventura-Backend.postman_environment.json
  ventura_backend/hprouting/serializers.py
  ventura_backend/hprouting/urls.py
  ventura_backend/requirements.txt
  ventura_backend/ventura/admin.py
  ventura_backend/ventura/models.py
  ventura_backend/ventura_backend/settings.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#31 Deployment issues. Env variables
  .gitignore
  ventura_backend/requirements.txt
  ventura_backend/ventura_backend/settings.py
Labels: bug, enhancement

#32 sslserver import issue
  ventura_backend/requirements.txt
Labels: bug
