Repository ISIS3510-202410-Team33/ventura-backend, pull requests merged in 2024-04, with the labels that each got.

#3 API development
  .gitignore
  ventura_backend/db.sqlite3
  ventura_backend/ventura/__init__.py
  ventura_backend/ventura/__pycache__/__init__.cpython-311.pyc
  ventura_backend/ventura/__pycache__/admin.cpython-311.pyc
  ventura_backend/ventura/__pycache__/apps.cpython-311.pyc
  ventura_backend/ventura/__pycache__/models.cpython-311.pyc
  ventura_backend/ventura/admin.py
  ventura_backend/ventura/api/__pycache__/serializer.cpython-311.pyc
  ventura_backend/ventura/api/__pycache__/urls.cpython-311.pyc
  ventura_backend/ventura/api/__pycache__/views.cpython-311.pyc
  ventura_backend/ventura/api/serializer.py
  ventura_backend/ventura/api/urls.py
  ventura_backend/ventura/api/views.py
  ventura_backend/ventura/apps.py
  ventura_backend/ventura/migrations/0001_initial.py
  ventura_backend/ventura/migrations/0002_colleges_users_delete_user.py
  ventura_backend/ventura/migrations/0003_remove_users_college_id_delete_colleges.py
  ventura_backend/ventura/migrations/0004_college_college_location_user_user_calification_and_more.py
  ventura_backend/ventura/migrations/__init__.py
  ventura_backend/ventura/migrations/__pycache__/0001_initial.cpython-311.pyc
  ventura_backend/ventura/migrations/__pycache__/0002_colleges_users_delete_user.cpython-311.pyc
  ventura_backend/ventura/migrations/__pycache__/0003_remove_users_college_id_delete_colleges.cpython-311.pyc
  ventura_backend/ventura/migrations/__pycache__/0004_college_college_location_user_user_calification_and_more.cpython-311.pyc
  ventura_backend/ventura/migrations/__pycache__/__init__.cpython-311.pyc
  ventura_backend/ventura/models.py
  ventura_backend/ventura/tests.py
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/__pycache__/__init__.cpython-311.pyc
  ventura_backend/ventura_backend/__pycache__/settings.cpython-311.pyc
  ventura_backend/ventura_backend/__pycache__/urls.cpython-311.pyc
  ventura_backend/ventura_backend/__pycache__/wsgi.cpython-311.pyc
  ventura_backend/ventura_backend/settings.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#4 API development
  .gitignore
  ventura_backend/db.sqlite3
  ventura_backend/ventura/__init__.py
  ventura_backend/ventura/admin.py
  ventura_backend/ventura/api/serializer.py
  ventura_backend/ventura/api/urls.py
  ventura_backend/ventura/api/views.py
  ventura_backend/ventura/apps.py
  ventura_backend/ventura/migrations/__init__.py
  ventura_backend/ventura/models.py
  ventura_backend/ventura/tests.py
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/settings.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#6 requirements.txt file created
  ventura_backend/requirements.txt
Labels: enhancement

#8 Implemented HTML pages in Django and the BQ5 usage from the web app
  ventura_backend/requirements.txt
  ventura_backend/ventura/static/images/goose.png
  ventura_backend/ventura/templates/base.html
  ventura_backend/ventura/templates/get_data.html
  ventura_backend/ventura/templates/index.html
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/settings.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#10 Feature/user-frequency-update-#9
  tempCodeRunnerFile.python
  ventura_backend/requirements.txt
  ventura_backend/ventura/api/views.py
  ventura_backend/ventura_backend/settings.py
Labels: enhancement

#13 Feature/api-documentation-#12
  ventura_backend/ventura/api/views.py
Labels: documentation, enhancement

#15 Implemented the new BQ for rating keywords of each building
  ventura_backend/ventura/templates/get_data.html
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#17 Added health-check/
  ventura_backend/requirements.txt
  ventura_backend/ventura/views.py
  ventura_backend/ventura_backend/urls.py
Labels: enhancement

#21 Implementation of analysis methods
  ventura_backend/ventura/api/urls.py
  ventura_backend/ventura/api/views.py
Labels: enhancement

#19 Requirements.txt library versions removed
  ventura_backend/requirements.txt
Labels: bug
